spring:
  application:
    name: kafka-customer-consumer

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: crm_customer
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

kafka:
  topic:
    register-customer: register_crm_customer