server:
  port: '8090'
spring:
  application:
    name: 'kafka-customer-producer'

  kafka:
    producer:
      bootstrap-servers: 'localhost:9092'
      key-serializer: 'org.apache.kafka.common.serialization.StringSerializer'
      value-serializer:  'io.confluent.kafka.serializers.KafkaAvroSerializer'
      properties:
        schema:
          registry:
            url: "http://localhost:8081"
        specific:
          avro:
            reader: true

  #Cache Configuration
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    timeout: 1000ms
    time-to-live: 3600
    key-prefix: crm-customer-service

kafka:
  topic:
    register-customer: 'register_crm_customer'
