server:
  port: 8090
spring:
  application:
    name: kafka-customer-producer

  kafka:
    bootstrap-servers:
      - "localhost:9092"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        auto:
          register:
            schemas: "true"
        schema:
          registry:
            url: "http://localhost:8081"
        specific:
          avro:
            reader: "true"

kafka:
  topic:
    register-customer: register_crm_customer
